/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * URLChooser1.java
 *
 * Created on May 28, 2011, 11:25:04 PM
 */

package org.sdrinovsky.sdsvn.tree;

/**
 *
 * @author sdrinovsky
 */
public class URLChooser extends javax.swing.JPanel {
  /**
   * Creates new form URLChooser1
   *
   * @param label
   * @param url
   */
  public URLChooser(String label, String url) {
    initComponents();
    messageLabel.setText(label);
    urlField.setText(url);
  }

  /**
   * Method getURL
   *
   *
   * @return
   *
   */
  public String getURL() {
    return urlField.getText();
  }

  /**
   * This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {
    messageLabel = new javax.swing.JLabel();
    urlField     = new javax.swing.JTextField();

    setName("Form");    // NOI18N

    org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(
       org.sdrinovsky.sdsvn.SVNApp.class).getContext().getResourceMap(URLChooser.class);

    messageLabel.setText(resourceMap.getString("messageLabel.text"));    // NOI18N
    messageLabel.setName("messageLabel");                                // NOI18N
    urlField.setText(resourceMap.getString("urlField.text"));            // NOI18N
    urlField.setName("urlField");                                        // NOI18N

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);

    this.setLayout(layout);
    layout.setHorizontalGroup(
       layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
         layout.createSequentialGroup().addContainerGap().addGroup(
           layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(
             urlField, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE).addComponent(
             messageLabel)).addContainerGap()));
    layout.setVerticalGroup(
       layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
         layout.createSequentialGroup().addContainerGap().addComponent(messageLabel).addPreferredGap(
           javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(
           urlField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
           javax.swing.GroupLayout.PREFERRED_SIZE).addContainerGap(
             javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
  }    // </editor-fold>//GEN-END:initComponents

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JLabel     messageLabel;
  private javax.swing.JTextField urlField;
  // End of variables declaration//GEN-END:variables
}
