/*
 * @(#) $Id$
 *
 * Copyright (c) 2010 Steven Drinovsky. All Rights Reserved.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 */

package org.sdrinovsky.sdsvn.tree;

/**
 *
 * @author sdrinovsky
 */
public class URLChooser extends javax.swing.JPanel {
  /**
   * Creates new form URLChooser
   *
   * @param label
   * @param url
   */
  public URLChooser(String label, String url) {
    initComponents();
    messageLabel.setText(label);
    urlField.setText(url);
  }

  /**
   * Method getURL
   *
   *
   * @return
   *
   */
  public String getURL() {
    return urlField.getText();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   *  WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {
    messageLabel = new javax.swing.JLabel();
    urlField     = new javax.swing.JTextField();

    setName("Form");                                                                                                 // NOI18N
    messageLabel.setText(org.openide.util.NbBundle.getMessage(URLChooser.class, "URLChooser.messageLabel.text"));    // NOI18N
    messageLabel.setName("messageLabel");                                                                    // NOI18N
    urlField.setText(org.openide.util.NbBundle.getMessage(URLChooser.class, "URLChooser.urlField.text"));    // NOI18N
    urlField.setName("urlField");                                                                            // NOI18N

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);

    this.setLayout(layout);
    layout.setHorizontalGroup(
       layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
         layout.createSequentialGroup().addContainerGap().addGroup(
           layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(
             urlField, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE).addComponent(
             messageLabel)).addContainerGap()));
    layout.setVerticalGroup(
       layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
         layout.createSequentialGroup().addContainerGap().addComponent(messageLabel).addPreferredGap(
           javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(
           urlField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
           javax.swing.GroupLayout.PREFERRED_SIZE).addContainerGap(
             javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
  }    // </editor-fold>//GEN-END:initComponents

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JLabel     messageLabel;
  private javax.swing.JTextField urlField;
  // End of variables declaration//GEN-END:variables
}
