/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AnnotateDialog.java
 *
 * Created on May 9, 2011, 10:49:06 PM
 */

package org.sdrinovsky.sdsvn.dialogs;

import java.awt.Component;

import javax.swing.JTable;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

import org.jdesktop.application.Action;

import org.sdrinovsky.sdsvn.files.FileTableRenderer;

/**
 *
 * @author sdrinovsky
 */
public class AnnotateDialog extends javax.swing.JDialog {
  long                             selectedRev     = -1;
  private DefaultTableCellRenderer coloredRenderer = new DefaultTableCellRenderer() {
    @Override
    public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus,
                                                   int r, int c) {
      Component comp = super.getTableCellRendererComponent(table, value, isSelected, hasFocus, r, c);
      Long      rev  = (Long)table.getModel().getValueAt(r, 1);

      if( !isSelected) {
        if(selectedRev == rev) {
          if(r % 2 == 0) {
            comp.setBackground(FileTableRenderer.alternateBlue);
          } else {
            comp.setBackground(FileTableRenderer.blue);
          }
        } else {
          if(r % 2 == 0) {
            comp.setBackground(FileTableRenderer.alternateColor);
          } else {
            comp.setBackground(FileTableRenderer.white);
          }
        }
      }

      return comp;
    }
  };

  /**
   * Creates new form AnnotateDialog
   *
   * @param parent
   * @param modal
   */
  public AnnotateDialog(java.awt.Frame parent, boolean modal) {
    super(parent, modal);

    initComponents();
    jTable1.setDefaultRenderer(Long.class, coloredRenderer);
    jTable1.setDefaultRenderer(String.class, coloredRenderer);
    jTable1.getColumnModel().getColumn(0).setPreferredWidth(65);
    jTable1.getColumnModel().getColumn(1).setPreferredWidth(65);
    jTable1.getColumnModel().getColumn(2).setPreferredWidth(85);
    jTable1.getColumnModel().getColumn(3).setPreferredWidth(655);
    jTable1.setAutoResizeMode(JTable.AUTO_RESIZE_NEXT_COLUMN);
    jTable1.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
      @Override
      public void valueChanged(ListSelectionEvent e) {
        if( !e.getValueIsAdjusting()) {
          int  selected       = jTable1.getSelectedRow();
          long newSelectedRev = (Long)jTable1.getValueAt(selected, 1);

          if(newSelectedRev != selectedRev) {
            selectedRev = newSelectedRev;

            jTable1.repaint();
          }
        }
      }
    });
  }

  /**
   * This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {
    jButton1     = new javax.swing.JButton();
    jScrollPane1 = new javax.swing.JScrollPane();
    jTable1      = new javax.swing.JTable();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    setName("Form");    // NOI18N

    javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(
       org.sdrinovsky.sdsvn.SVNApp.class).getContext().getActionMap(AnnotateDialog.class, this);

    jButton1.setAction(actionMap.get("close"));    // NOI18N
    jButton1.setName("jButton1");                  // NOI18N
    jScrollPane1.setName("jScrollPane1");          // NOI18N
    jTable1.setModel(new javax.swing.table.DefaultTableModel(new Object[][]{
    }, new String[]{"Line", "Revision", "Author", "Text"}) {
      Class[] types = new Class[]{java.lang.Long.class, java.lang.Long.class, java.lang.String.class,
                                  java.lang.String.class};
      public Class getColumnClass(int columnIndex) {
        return types[columnIndex];
      }
    });
    jTable1.setName("jTable1");    // NOI18N
    jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
    jScrollPane1.setViewportView(jTable1);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());

    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
       layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
         javax.swing.GroupLayout.Alignment.TRAILING,
         layout.createSequentialGroup().addContainerGap(887, Short.MAX_VALUE).addComponent(
           jButton1).addContainerGap()).addComponent(
             jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 950, Short.MAX_VALUE));
    layout.setVerticalGroup(
       layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
         javax.swing.GroupLayout.Alignment.TRAILING,
         layout.createSequentialGroup().addComponent(
           jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 447, Short.MAX_VALUE).addPreferredGap(
           javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(jButton1).addContainerGap()));

    java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();

    setBounds((screenSize.width - 950) / 2, (screenSize.height - 524) / 2, 950, 524);
  }    // </editor-fold>//GEN-END:initComponents

  /**
   * Method close
   *
   *
   */
  @Action
  public void close() {
    setVisible(false);
  }

  /**
   * Method addRow
   *
   *
   * @param row
   *
   */
  public void addRow(Object[] row) {
    ((DefaultTableModel)jTable1.getModel()).addRow(row);
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton     jButton1;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JTable      jTable1;
  // End of variables declaration//GEN-END:variables
}
