/**
 * A JavaNCSSClassMetric contains metrics about a class that were generated by JavaNCSS.
 * Provides the following information about a class:
 * - The class name
 * - The fully qualified class name
 * - The number of methods contained within a class
 * - The average method length for the methods in the class
 * - The code complexity number  (CCN or McCabe Metric) for the class
 * - The code complexity density (CCN / Total NCSS Method Sum)
 * @author Jeremy
 */
public class JavaNCSSClassMetric {
	private String qualifiedClassName;
	private String className;
	private int numMethods;
	private float averageMethodLength;
	private int complexityNumber;
	private float complexityDensity;
	
	JavaNCSSClassMetric(String qualifiedClassName, String className, 
			int numMethods, float averageMethodLength, int complexityNumber, 
			float complexityDensity) {
		this.qualifiedClassName = qualifiedClassName;
		this.className = className;
		this.numMethods = numMethods;
		this.averageMethodLength = averageMethodLength;
		this.complexityNumber = complexityNumber;
		this.complexityDensity = complexityDensity;
	}
		
	public String getQualifiedClassName() {
		return qualifiedClassName;
	}
	
	public String getClassName() {
		return className;
	}
	
	public int getNumMethods() {
		return numMethods;
	}
	
	public float getAverageMethodLength() {
		return averageMethodLength;
	}
	
	public int getComplexityNumber () {
		return complexityNumber;
	}
	
	public float getComplexityDensity() {
		return complexityDensity;
	}
}

