/**
 * A JavaNCSSClassMetric contains metrics about a class that were generated by JavaNCSS.
 * Provides the following information about a class:
 * - The class name
 * - The fully qualified class name
 * - The number of methods contained within a class
 * - The average method length for the methods in the class
 * @author Jeremy
 */
public class JavaNCSSClassMetric {
	private String qualifiedClassName;
	private String className;
	private int numMethods;
	private float averageMethodLength;
	
	JavaNCSSClassMetric(String qualifiedClassName, String className, int numMethods, float averageMethodLength) {
		this.qualifiedClassName = qualifiedClassName;
		this.className = className;
		this.numMethods = numMethods;
		this.averageMethodLength = averageMethodLength;
	}
		
	public String getQualifiedClassName() {
		return qualifiedClassName;
	}
	
	public String getClassName() {
		return className;
	}
	
	public int getNumMethods() {
		return numMethods;
	}
	
	public float getAverageMethodLength() {
		return averageMethodLength;
	}
}

